#!/usr/bin/env bash
# gen-types.sh — derive the frontend API contract types from the Go
# handlers' payloads (source of truth: Go structs in internal/).
# Output: web/src/api-types.d.ts  (checked into the repo; regen on change)
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=web/src/api-types.d.ts
cat > "$OUT" <<'EOF'
// AUTO-GENERATED by scripts/gen-types.sh — do not edit by hand.
// Mirrors the Go types consumed by the HTTP API (internal/{server,store,runner}).
// Regenerate with: scripts/gen-types.sh

export interface Agent {
  id: string;
  label: string;
  color: string;
}

export interface Session {
  id: string;
  agent: string;
  title: string;
  agent_ref: string;
  cwd?: string;
  created_at: string;
  updated_at: string;
  message_count: number;
  preview: string;
}

export type SessionStatus = "idle" | "running" | "waiting";

export interface Message {
  id: number;
  session_id: string;
  role: "user" | "assistant";
  content: string;
  meta: MessageMeta | null;
  created_at: string;
}

export interface MessageMeta {
  agent?: string;
  tools?: ToolRecord[];
  error?: boolean;
  error_message?: string;
  [k: string]: unknown;
}

export interface ToolRecord {
  name: string;
  state: string;
  detail?: string;
}

// SSE events (server -> client). `type` discriminates.
export type StreamEvent =
  | { type: "state"; running: boolean; status: SessionStatus }
  | { type: "queue"; count: number }
  | { type: "text"; content: string }
  | { type: "tool"; name: string; state: string; detail?: string }
  | { type: "permission"; request_id: string; tool: string; input: string }
  | { type: "message_end"; message: Message };

// POST /api/sessions
export interface CreateSessionIn {
  agent: string;
  title?: string;
  cwd?: string;
}

// POST /api/sessions/{id}/messages -> 200 | 202
export interface SendOut {
  ok: boolean;
  queued: boolean;
}

// POST /api/sessions/{id}/control
export interface ControlIn {
  request_id: string;
  behavior: "allow" | "deny";
  updatedInput?: unknown;
}

// GET /api/server/port
export interface PortInfo {
  serving: number;
  configured: string;
}

// PUT /api/server/port -> 202
export interface PortMoving {
  moving: boolean;
  port: number;
}

// GET /api/server-info
export interface ServerInfo {
  mode: string;
  version: string;
  user: string;
  host: string;
}

// GET /api/fs/dirs
export interface FsDirs {
  path: string;
  dirs: { name: string; path: string }[];
}
EOF
echo "types written to $OUT"
echo "NOTE: kept in sync by review — CI smoke (go test + web tests) catch drift at runtime."
